//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvbLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvbKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nvbKhoa()
        {
            this.nvbSinhViens = new HashSet<nvbSinhVien>();
        }
    
        public string NvbMaKH { get; set; }
        public string NvbTenKH { get; set; }
        public Nullable<bool> NvbTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nvbSinhVien> nvbSinhViens { get; set; }
    }
}
