//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvbLesson09Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NvbK22CNT2Lesson09DbEntities : DbContext
    {
        public NvbK22CNT2Lesson09DbEntities()
            : base("name=NvbK22CNT2Lesson09DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nvbKhoa> nvbKhoas { get; set; }
        public virtual DbSet<nvbSinhVien> nvbSinhViens { get; set; }
    }
}
