//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvbLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvbSinhVien
    {
        public string NvbMaSV { get; set; }
        public string NvbHoSV { get; set; }
        public string NvbTenSV { get; set; }
        public Nullable<System.DateTime> NvbNgaySinh { get; set; }
        public Nullable<bool> NvbPhai { get; set; }
        public string NvbPhone { get; set; }
        public string NvbEmail { get; set; }
        public string NvbMaKH { get; set; }
    
        public virtual nvbKhoa nvbKhoa { get; set; }
    }
}
